name: deploy-docs

on:
    push:
        tags: "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
    deploy-docs:
        name: Deploy Docs on GitHub Pages
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: "15"
            - name: Install dependencies
              run: yarn install
            - name: Build docs
              run: yarn run docs
            - name: Deploy docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
                  publish_branch: docs
                  keep_files: true
    update-version-list:
        name: Upate version list in index.html file
        runs-on: ubuntu-20.04
        needs: deploy-docs
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: docs
            - name: Update version list in docs/index.html
              run: sed -Ei "s/\{\{\s*VERSIONS\s*\}\}/$( ls -d1 v* | paste -sd ',' )/" ./index.html
            - name: Push to branch
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add ./index.html
                  git commit -m "Update version list"
                  git push
