name: deploy-docs

on:
    push:
        tags: "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
    deploy-docs:
        name: Deploy Docs on GitHub Pages
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: "15"
            - name: Install dependencies
              run: yarn install
            - name: Build docs
              run: yarn run docs
            - name: Update version list in docs/index.html
              run: |
                  cd ./docs && \
                  sed -Ei "s/\{\{\s*VERSIONS\s*\}\}/$( ls -dx v* )/" ./index.html
            - name: Deploy docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
                  publish_branch: docs
